# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de742c2ab75a5a476df259bd3f722c0ab14abd74d732effc6b1a010d0650d275d3a3ef5ccd165d7a368b0da64585c7c4dcf4c4a493b4bd7bc33f27f3704fa6e0

test:
  secret_key_base: 0b35dc16dd1d42cfe19882afd404b6d6d9161f1a83b6b7fed9072bc627199e98c5a49fab4ebdf78b9359b13bffdb9d9985711404ed31a03ab65edc3eb2e7860e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
